package com.iox.lexer;
/*
 * Token class will have every single
 * token generated by the Tokenizer. 
 */
public class Token {
	public TokenType type;
	public String value;
	public int lineNumber;
	public int columnNumber;
	/*
	 * Token single Constructor.
	 */
	public Token(TokenType type, String value) {
		this.type = type;
		this.value = value;
	}
	/*
	 * Token Full Constructor.
	 */
	public Token(TokenType type, String value, int lineNumber, int columnNumber) {
		this.type = type;
		this.value = value;
		this.lineNumber = lineNumber;
		this.columnNumber = columnNumber;
	}
}
